platform :ios, '10.0'
target 'JTFaceAttendence' do
pod 'ReactiveObjC'
pod 'SDWebImage'
pod 'AFNetworking'
pod 'DZNEmptyDataSet'
pod 'Masonry', '~> 1.1.0'
pod 'MJRefresh'
pod 'MJExtension'
pod 'SVProgressHUD'
end